// This is the complete application IPC contract. Never expose raw ipcRenderer.
module.exports = {
  requests: [
    'organizer:state', 'organizer:analyze', 'organizer:apply', 'organizer:group',
    'organizer:move', 'organizer:workspace', 'organizer:select-workspace', 'organizer:pin',
    'organizer:sleep', 'organizer:wake', 'organizer:close-duplicates',
    'organizer:save-session', 'organizer:restore-session', 'organizer:delete-session', 'organizer:summary', 'organizer:undo',
    'screentime:state', 'screentime:update', 'screentime:save-rule', 'screentime:remove-rule',
    'screentime:preset', 'screentime:clear-usage', 'screentime:unlock',
    'app:state', 'ui:layout', 'ui:shortcuts', 'ui:action', 'ui:suggestions',
    'window:control', 'menu:open', 'menu:state', 'menu:ready', 'menu:pending', 'context:run', 'find:query', 'find:close', 'wallpapers:catalog', 'wallpapers:random', 'import:detect', 'import:run', 'autofill:choose', 'autofill:decide', 'autofill:state', 'autofill:list', 'autofill:values', 'autofill:put', 'autofill:remove', 'autofill:prefs', 'autofill:never-remove', 'passwords:export', 'passwords:import', 'passwords:health', 'passwords:breach-check', 'help:system', 'help:reveal', 'feedback:categories', 'feedback:available', 'feedback:attach', 'feedback:screenshot', 'feedback:shots', 'feedback:remove', 'feedback:preview', 'feedback:submit', 'feedback:reveal', 'split:resize', 'split:reset', 'split:swap', 'split:exit', 'split:with', 'split:drag', 'split:drop', 'split:menu',
    'tabs:new', 'tabs:open-files', 'tabs:close', 'tabs:select', 'tabs:reorder', 'tabs:navigate',
    'navigation:back', 'navigation:forward', 'navigation:reload', 'navigation:stop', 'navigation:home',
    'omnibox:suggest', 'bookmarks:toggle', 'bookmarks:remove',
    'history:search', 'history:remove',
    'extensions:load-unpacked', 'extensions:load-crx', 'extensions:set-enabled', 'extensions:remove', 'extensions:options',
    'downloads:reveal', 'downloads:cancel', 'downloads:clear',
    'settings:update', 'settings:clear-data', 'settings:reset',
    'newtab:notes', 'newtab:wallpaper',
    'profiles:state', 'profiles:enter', 'profiles:create', 'profiles:update',
    'profiles:remove', 'profiles:duplicate', 'profiles:clear-data', 'profiles:set-default',
    'profiles:set-pin', 'profiles:startup', 'profiles:manage', 'profiles:switch',
    'onboarding:state', 'onboarding:next', 'onboarding:back', 'onboarding:skip',
    'onboarding:profile', 'onboarding:layout', 'onboarding:theme', 'onboarding:privacy', 'onboarding:ai',
    'onboarding:complete', 'onboarding:restart',
    'ai:ask', 'ai:ask-page', 'ai:cancel', 'ai:status', 'ai:page-permission', 'ai:summarise-page', 'ai:explain-selection', 'ai:formats', 'sidebar:toggle', 'sidebar:state', 'sidebar:peek', 'sidebar:panel', 'health:report', 'health:fix', 'sense:current', 'sense:accept', 'sense:snooze', 'sense:silence', 'sense:state', 'sense:enabled',
    'chat:list', 'chat:get', 'chat:new', 'chat:send',
    'chat:rename', 'chat:pin', 'chat:delete', 'chat:clear',
    'resources:state', 'resources:update', 'resources:suspend', 'resources:resume',
    'resources:resume-all', 'resources:game-mode', 'resources:watch',
    'focus:state', 'focus:start', 'focus:stop', 'focus:update', 'focus:unlock',
    'notes:list', 'notes:add', 'notes:update', 'notes:remove', 'notes:state',
    'notes:capture', 'notes:screenshot', 'notes:export', 'notes:summarise',
    'notes:workspace-add', 'notes:workspace-remove', 'notes:workspace-select',
    'safety:state', 'safety:assess', 'safety:trust', 'safety:untrust',
    'safety:enabled', 'safety:proceed',
    'modes:state',
    'shields:state', 'shields:update', 'shields:site', 'shields:report', 'shields:refresh',
    'shields:stats', 'shields:activity', 'shields:reset-stats',
    'passwords:state', 'passwords:list', 'passwords:save', 'passwords:for-url',
    'passwords:reveal', 'passwords:remove', 'passwords:clear', 'passwords:generate',
    'passwords:lock-state', 'passwords:set-master', 'passwords:change-master', 'passwords:remove-master',
    'passwords:unlock', 'passwords:unlock-device', 'passwords:lock', 'passwords:device', 'passwords:lock-after',
    'passwords:passkeys', 'passwords:remove-passkey', 'passwords:answer', 'passwords:unlock-menu', 'autofill:no-auto-remove',
    'passwords:add', 'passwords:update', 'passwords:details', 'passwords:key-menu', 'menu:passthrough',
    'workspace:tasks', 'workspace:page-text', 'workspace:run', 'shopping:compare',
  ],
  events: ['wallpapers:changed', 'find:result', 'find:focus', 'app:state', 'ui:focus-address', 'ui:notice', 'ui:open-menu', 'ui:render-menu', 'ui:menu-closed', 'ui:menu-focus', 'chat:changed', 'resources:changed', 'focus:changed', 'notes:changed', 'safety:changed', 'shields:changed', 'passwords:changed', 'organizer:changed', 'screentime:changed'],
};
