// This is the complete application IPC contract. Never expose raw ipcRenderer.
module.exports = {
  requests: [
    'organizer:state', 'organizer:analyze', 'organizer:apply', 'organizer:group',
    'organizer:move', 'organizer:workspace', 'organizer:select-workspace', 'organizer:pin',
    'organizer:sleep', 'organizer:wake', 'organizer:close-duplicates',
    'organizer:save-session', 'organizer:restore-session', 'organizer:delete-session', 'organizer:summary', 'organizer:undo',
    'screentime:state', 'screentime:update', 'screentime:save-rule', 'screentime:remove-rule',
    'screentime:preset', 'screentime:clear-usage', 'screentime:unlock',
    'app:state', 'ui:layout', 'ui:shortcuts', 'ui:action',
    'window:control', 'menu:open', 'menu:state', 'menu:ready', 'menu:pending',
    'tabs:new', 'tabs:close', 'tabs:select', 'tabs:reorder', 'tabs:navigate',
    'navigation:back', 'navigation:forward', 'navigation:reload', 'navigation:stop', 'navigation:home',
    'omnibox:suggest', 'bookmarks:toggle', 'bookmarks:remove',
    'history:search', 'history:remove',
    'extensions:load-unpacked', 'extensions:load-crx', 'extensions:set-enabled', 'extensions:remove', 'extensions:options',
    'downloads:reveal', 'downloads:cancel', 'downloads:clear',
    'settings:update', 'settings:clear-data', 'settings:reset',
    'newtab:notes',
    'ai:ask', 'ai:cancel', 'ai:status',
    'chat:list', 'chat:get', 'chat:new', 'chat:send',
    'chat:rename', 'chat:pin', 'chat:delete', 'chat:clear',
    'resources:state', 'resources:update', 'resources:suspend', 'resources:resume',
    'resources:resume-all', 'resources:game-mode', 'resources:watch',
    'focus:state', 'focus:start', 'focus:stop', 'focus:update', 'focus:unlock',
    'notes:list', 'notes:add', 'notes:update', 'notes:remove', 'notes:state',
    'notes:capture', 'notes:screenshot', 'notes:export', 'notes:summarise',
    'notes:workspace-add', 'notes:workspace-remove', 'notes:workspace-select',
    'safety:state', 'safety:assess', 'safety:trust', 'safety:untrust',
    'safety:enabled', 'safety:proceed',
    'modes:state',
    'shields:state', 'shields:update', 'shields:site', 'shields:report', 'shields:refresh',
    'passwords:state', 'passwords:list', 'passwords:save', 'passwords:for-url',
    'passwords:reveal', 'passwords:remove', 'passwords:clear', 'passwords:generate',
    'workspace:tasks', 'workspace:page-text', 'workspace:run', 'shopping:compare',
  ],
  events: ['app:state', 'ui:focus-address', 'ui:notice', 'ui:open-menu', 'ui:render-menu', 'ui:menu-closed', 'chat:changed', 'resources:changed', 'focus:changed', 'notes:changed', 'safety:changed', 'shields:changed', 'organizer:changed', 'screentime:changed'],
};
