const { build } = require('esbuild');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Pre-build Brave's YouTube scriptlet bundle.
 *
 * The preload is SANDBOXED: it cannot read a file at runtime, so resolving the
 * scriptlets from resources.json there silently produced nothing and the
 * scriptlets never ran. The bundle is therefore built here, at build time, and
 * emitted as a module the preload simply imports.
 *
 * It is generated rather than committed so it can never drift from
 * resources.json and youtube-rules.json.
 */
function buildYouTubeScriptlets() {
  const out = path.join(__dirname, '..', 'src', 'features', 'shields', 'brave', 'youtube-bundle.js');
  let source = '';
  try {
    const brave = require('../src/features/shields/brave');
    source = brave.youtubeBundle();
    console.log('brave: ' + brave.youtubeRuleCount() + ' YouTube rules, ' +
      Math.round(source.length / 1024) + ' KB of scriptlets');
  } catch (error) {
    // A failure here must not stop the browser building: the rest of the
    // blocking still works without these scriptlets.
    console.error('brave: could not build the scriptlet bundle:', error.message);
  }
  fs.writeFileSync(out,
    '// GENERATED by scripts/build.cjs - do not edit.\n' +
    '// Brave\'s YouTube scriptlets (MPL-2.0), pre-built because a sandboxed\n' +
    '// preload cannot read resources.json at runtime.\n' +
    'module.exports = ' + JSON.stringify(source) + ';\n');
}

buildYouTubeScriptlets();

// Preloads must be bundled: sandboxed preloads cannot `require` from
// node_modules at runtime, and chrome.js pulls in electron-chrome-extensions'
// browser-action element. Output is CommonJS because preloads are not ESM.
const targets = [
  { entryPoints: ['src/preload/chrome.js'], outfile: 'build/chrome.preload.cjs' },
  { entryPoints: ['src/preload/tab.js'], outfile: 'build/tab.preload.cjs' },
];

Promise.all(targets.map(target => build({
  ...target,
  bundle: true, platform: 'node', format: 'cjs', external: ['electron'],
  target: 'node22', sourcemap: false,
}))).catch(error => { console.error(error); process.exit(1); });
